### PR TITLE
Refactor demo and test to reflect change from DeaconService to MeteorPushReceiver

### PR DESCRIPTION
**Pull request by lkorth**

### CODE REVIEW

**Comment by davidrea** [comment]
Luke - Thank you for your contribution!

**Comment by lkorth** [comment]
Not a problem, I look forward to using it. There also seems to be an similar issue with the demo android app with the variable Deacon but I have not looked at it enough yet to be sure if it's the same problem.

**Comment by davidrea** [comment]
Yes, the demo app is still tied to the older API. Now that I have some more experience with them, I realize the correct way to link the demo app into Deacon is to use a git submodule. This way the demo app's Deacon instance can point to a specific Deacon repository commit, enforcing API synchronization.

But yes, ultimately, it needs to be updated.

**Comment by lkorth** [comment]
Ok, I plan on using Deacon so I may end up updating it.

**Pull request merged**
